# https://travis-ci.org/soimort/you-get
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial    
    - python: "nightly"
      dist: xenial    
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2'* && $TRAVIS_PYTHON_VERSION != '3.3'* ]]; then pip install flake8; fi
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2'* && $TRAVIS_PYTHON_VERSION != '3.3'* ]]; then flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics; fi
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/43cd57826e88ed8f2152
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
